const APP_VERSION = "20261009110911";
const STATIC_CACHE = `roborally-static-${APP_VERSION}`;
const RUNTIME_CACHE = `roborally-runtime-${APP_VERSION}`;

// PRECACHE LIST START (generated by scripts/stamp-version.cjs; do not edit by hand)
const UNVERSIONED_ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./assets/icons/apple-touch-icon.png",
  "./assets/icons/favicon-16.png",
  "./assets/icons/favicon-24.png",
  "./assets/icons/favicon-32.png",
  "./assets/icons/favicon.ico",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png"
];
const VERSIONED_ASSETS = [
  "./analyze.js",
  "./board.js",
  "./course-notes.js",
  "./feature-meta.js",
  "./feature-weights.js",
  "./main.js",
  "./render.js",
  "./src/analysis/analysis-state.js",
  "./src/analysis/board-ablation.js",
  "./src/analysis/board-geometry.js",
  "./src/analysis/collections.js",
  "./src/analysis/constants.js",
  "./src/analysis/contextual-search.js",
  "./src/analysis/course-analysis.js",
  "./src/analysis/damage-economy.js",
  "./src/analysis/damage-routing.js",
  "./src/analysis/energy-economy.js",
  "./src/analysis/flag-area.js",
  "./src/analysis/full-course.js",
  "./src/analysis/movement.js",
  "./src/analysis/physical-cache.js",
  "./src/analysis/program-availability.js",
  "./src/analysis/program-demand.js",
  "./src/analysis/re-diagnostics.js",
  "./src/analysis/re-ledger.js",
  "./src/analysis/reboot-recovery.js",
  "./src/analysis/route-evaluation.js",
  "./src/analysis/route-pricing-economy.js",
  "./src/analysis/route-search.js",
  "./src/analysis/route-selection.js",
  "./src/analysis/rule-options.js",
  "./src/analysis/telemetry.js",
  "./src/analysis/traffic.js",
  "./src/generation/analysis-orchestration.js",
  "./src/generation/assets.js",
  "./src/generation/board-layout.js",
  "./src/generation/board-profile.js",
  "./src/generation/board-selection.js",
  "./src/generation/calibration-features.js",
  "./src/generation/calibration-hooks.js",
  "./src/generation/candidate-builder.js",
  "./src/generation/candidate-selection.js",
  "./src/generation/checkpoints.js",
  "./src/generation/classification.js",
  "./src/generation/competitive.js",
  "./src/generation/config.js",
  "./src/generation/construction-cleanup.js",
  "./src/generation/construction-guidance.js",
  "./src/generation/course-quality.js",
  "./src/generation/dev-replay.js",
  "./src/generation/diagnostics.js",
  "./src/generation/difficulty-metrics.js",
  "./src/generation/environment.js",
  "./src/generation/fingerprints.js",
  "./src/generation/generation-loop.js",
  "./src/generation/generation-modes.js",
  "./src/generation/guidance-calibration.js",
  "./src/generation/labels.js",
  "./src/generation/layout-geometry.js",
  "./src/generation/length-metrics.js",
  "./src/generation/math.js",
  "./src/generation/moving-targets.js",
  "./src/generation/no-docks.js",
  "./src/generation/overlays.js",
  "./src/generation/persistence.js",
  "./src/generation/play-time.js",
  "./src/generation/preferences.js",
  "./src/generation/random.js",
  "./src/generation/reboot-tokens.js",
  "./src/generation/route-field.js",
  "./src/generation/scheduling.js",
  "./src/generation/start-balance.js",
  "./src/generation/start-pricing.js",
  "./src/generation/targets.js",
  "./src/generation/variant-availability.js",
  "./src/generation/virtual-bots.js",
  "./src/shared/math.js",
  "./src/ui/app.js",
  "./src/ui/board-audit.js",
  "./src/ui/build-info.js",
  "./src/ui/controls.js",
  "./src/ui/dev-view.js",
  "./src/ui/dialogs.js",
  "./src/ui/generation-overlay.js",
  "./src/ui/map-view.js",
  "./src/ui/reports.js",
  "./src/ui/rules-notes.js",
  "./src/ui/setup-summary.js",
  "./src/ui/state.js",
  "./src/ui/toast.js",
  "./variants.js",
  "./data/30th-docking-bay-a.json",
  "./data/30th-docking-bay-b.json",
  "./data/all-roads.json",
  "./data/assembly.json",
  "./data/black-gold.json",
  "./data/blueprint.json",
  "./data/cactus.json",
  "./data/chasm.json",
  "./data/circles.json",
  "./data/circuit-trap.json",
  "./data/coliseum.json",
  "./data/coming-and-going.json",
  "./data/concentric.json",
  "./data/confusion.json",
  "./data/convergence.json",
  "./data/discovery.json",
  "./data/docking-bay-a.json",
  "./data/docking-bay-b.json",
  "./data/double-helix.json",
  "./data/double-zap.json",
  "./data/doubles.json",
  "./data/energize.json",
  "./data/falling.json",
  "./data/fireball-factory.json",
  "./data/flood-zone.json",
  "./data/gauntlet-of-fire.json",
  "./data/gear-box.json",
  "./data/in-and-out.json",
  "./data/labyrinth.json",
  "./data/laser-maze.json",
  "./data/links.json",
  "./data/locked.json",
  "./data/mb-docking-bay-a.json",
  "./data/mb-docking-bay-b.json",
  "./data/mb-tile-10a.json",
  "./data/mb-tile-10b.json",
  "./data/mb-tile-11a.json",
  "./data/mb-tile-11b.json",
  "./data/mb-tile-12a.json",
  "./data/mb-tile-12b.json",
  "./data/mb-tile-13a.json",
  "./data/mb-tile-13b.json",
  "./data/mb-tile-14a.json",
  "./data/mb-tile-14b.json",
  "./data/mb-tile-15a.json",
  "./data/mb-tile-15b.json",
  "./data/mb-tile-16a.json",
  "./data/mb-tile-16b.json",
  "./data/mb-tile-17a.json",
  "./data/mb-tile-17b.json",
  "./data/mb-tile-1a.json",
  "./data/mb-tile-1b.json",
  "./data/mb-tile-2a.json",
  "./data/mb-tile-2b.json",
  "./data/mb-tile-3a.json",
  "./data/mb-tile-3b.json",
  "./data/mb-tile-4a.json",
  "./data/mb-tile-4b.json",
  "./data/mb-tile-5a.json",
  "./data/mb-tile-5b.json",
  "./data/mb-tile-6a.json",
  "./data/mb-tile-6b.json",
  "./data/mb-tile-7a.json",
  "./data/mb-tile-7b.json",
  "./data/mb-tile-8a.json",
  "./data/mb-tile-8b.json",
  "./data/mb-tile-9a.json",
  "./data/mb-tile-9b.json",
  "./data/meeple.json",
  "./data/mergers.json",
  "./data/merry-go-round.json",
  "./data/misdirection.json",
  "./data/portal-palace.json",
  "./data/pushy.json",
  "./data/reactor-core.json",
  "./data/sampler.json",
  "./data/sidewinder.json",
  "./data/spin-class.json",
  "./data/steps.json",
  "./data/stop-and-go.json",
  "./data/straight-a-ways.json",
  "./data/styx.json",
  "./data/tabula-rasa.json",
  "./data/tempest.json",
  "./data/the-abyss.json",
  "./data/the-h.json",
  "./data/the-keep.json",
  "./data/the-o-ring.json",
  "./data/the-oval.json",
  "./data/the-pits.json",
  "./data/the-wave.json",
  "./data/the-x.json",
  "./data/the-zone.json",
  "./data/toasted.json",
  "./data/transition.json",
  "./data/trench-run.json",
  "./data/vacancy.json",
  "./data/water-park.json",
  "./data/whirlpool.json",
  "./data/winding.json",
  "./calibration/construction-guidance.json"
];
// PRECACHE LIST END

const PRECACHE_URLS = [
  ...UNVERSIONED_ASSETS,
  ...VERSIONED_ASSETS.map((path) => `${path}?v=${APP_VERSION}`)
];
// Board photos (96, ~18 MB) live in the runtime cache; keep room for all of them.
const RUNTIME_CACHE_LIMIT = 160;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) => cache.addAll(PRECACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const cacheNames = await caches.keys();
    await Promise.all(
      cacheNames
        .filter((name) => name !== STATIC_CACHE && name !== RUNTIME_CACHE)
        .map((name) => caches.delete(name))
    );
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const { request } = event;

  if (request.method !== "GET") {
    return;
  }

  const url = new URL(request.url);

  if (url.origin !== self.location.origin) {
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(networkFirst(request, STATIC_CACHE));
    return;
  }

  event.respondWith(precachedOrStaleWhileRevalidate(request));
});

// Precached files are installed as one set per app version and replaced together,
// so they are served straight from the precache. Everything else (board photos)
// goes through the runtime cache.
async function precachedOrStaleWhileRevalidate(request) {
  const precached = await caches.match(request, { cacheName: STATIC_CACHE });
  return precached || staleWhileRevalidate(request, RUNTIME_CACHE);
}

async function networkFirst(request, cacheName) {
  const cache = await caches.open(cacheName);

  try {
    const response = await fetch(request);
    if (response.ok) {
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    return (await cache.match(request)) || cache.match("./index.html");
  }
}

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);

  const networkPromise = fetch(request)
    .then((response) => {
      if (response.ok) {
        cache.put(request, response.clone());
        trimCache(cacheName, RUNTIME_CACHE_LIMIT).catch(() => null);
      }
      return response;
    })
    .catch(() => null);

  if (cached) {
    networkPromise.catch(() => null);
    return cached;
  }

  const response = await networkPromise;
  return response || new Response("Offline and no cached response available.", {
    status: 504,
    statusText: "Gateway Timeout",
    headers: { "Content-Type": "text/plain; charset=utf-8" }
  });
}

async function trimCache(cacheName, maxEntries) {
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  if (keys.length <= maxEntries) {
    return;
  }

  await Promise.all(keys.slice(0, keys.length - maxEntries).map((request) => cache.delete(request)));
}
